name: alertyd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask=1.1.2
  - flask-restful=0.3.8
  - flask-sqlalchemy=2.4.3
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - markupsafe=2.0.1
  - pytz=2020.1
  - six=1.15.0
  - sqlalchemy=1.3.18
  - werkzeug=1.0.1
  - feedparser=6.0.10
  - requests=2.24.0
  - python-dotenv
  - pip
  - pip:
    - aniso8601==8.0.0
